name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    env:
      POSTGRES_URL: "postgres://default:4cWDkEjigN0G@ep-long-grass-43596317-pooler.us-east-1.postgres.vercel-storage.com:5432/verceldb"
      POSTGRES_PRISMA_URL: "postgres://default:4cWDkEjigN0G@ep-long-grass-43596317-pooler.us-east-1.postgres.vercel-storage.com:5432/verceldb?pgbouncer=true&connect_timeout=15"
      POSTGRES_URL_NON_POOLING: "postgres://default:4cWDkEjigN0G@ep-long-grass-43596317.us-east-1.postgres.vercel-storage.com:5432/verceldb"
      POSTGRES_USER: "default"
      POSTGRES_HOST: "ep-long-grass-43596317-pooler.us-east-1.postgres.vercel-storage.com"
      POSTGRES_PASSWORD: "4cWDkEjigN0G"
      POSTGRES_DATABASE: "verceldb"
      AUTH_SECRET: "jOPNILB5Sgx8dKj0avttB6evOq/5RtlAfodJQmKcWXo="
      AUTH_URL: "http://localhost:3000/api/auth"
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_DUNE_05A39D900 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: ""

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_DUNE_05A39D900 }}
          action: "close"
